### PR TITLE
Feature/move theme token calc

### PR DESCRIPTION
**Pull request by auronsan1st**
add calc on styles when use theme token. 
need careful on operator (+ and -), the number without `px` will return invalid css.

### CODE REVIEW

**Comment by rtivital** [comment]
@auronsan1st seems like these changes broke rte package compatibility with system props

**Comment by auronsan** [comment]
@rtivital fixed. my bad missing a parenthesis.

**Comment by rtivital** [comment]
@auronsan1st Have you checked whether there are any visual differences after migration?

**Comment by auronsan** [comment]
- [ ] Accordion
- [ ] AccordionPanel
- [ ] Badge
- [ ] Burger
- [ ] Code
- [ ] Dialog
- [ ] Indicator
- [ ] Input
- [ ] Kbd
- [ ] MenuDivider
- [ ] MenuLabel
- [ ] MutliSelect
- [ ] Marks
- [ ] Thumb
- [ ] Step
- [ ] Stepper
- [ ] TabList
- [ ] TimelineItem
- [ ] Tooltip
- [ ] RenderList
- [ ] TypographyStylesProvider
- [ ] Month
- [ ] CodeDemo
- [ ] TagInput
- [ ] RichTextEditor
- [ ] Toolbar
- [ ] ActionList

**Comment by rtivital** [comment]
Alright, please ping me once you are done

**Comment by auronsan** [comment]
@rtivital done checked.

**Pull request merged**
