### PR TITLE
Group component

### PR DESCRIPTION
**Pull request by achmurali**
- Added an additional `gutter` prop in **Group** component, signifying padding for the root element (Issue #196). 
- Fixed `404` page, added margin between navbar and main content.

image

### CODE REVIEW

**Comment by rtivital** [comment]
All right, this change to Group seems reasonable and should not break anything, thanks for working on this.
Can you also make these changes:
- Rename `gutter` prop to `withGutter` (gutter usually assumes some value, e.g. `gutter={12} or gutter="sm"`)
- Wrap 404 page in Container so it does not look so inconsistent with the rest of the docs

**Comment by achmurali** [comment]
Hi @rtivital, have a minor issue ( I think ), because the [splitCamelCase](https://github.com/mantinedev/mantine/blob/master/docs/src/components/Demo/Configurator/controls/BooleanControl.tsx#L11) function in BooleanControl capitalizes the first letter of a string, the mantine docs displays it as `With gutter` and not something like `with Gutter` or `With Gutter`.

Let me know if i should fix this- 
- By either giving an option to specify the explicit string to be displayed.
- or capitalize first letter of every word.

**Comment by rtivital** [comment]
It's correct – `With gutter` is more human readable label than `withGutter`, it does not affect demo code

**Comment by achmurali** [comment]
I am talking about the capitalisation. Currently it is displayed as 'With gutter' and i think 'With Gutter' (capital G ) would look good.

**Comment by rtivital** [comment]
That's Not How We Usually Write Text Or Labels In Application, Look A Little Bit Odd If You Capitalize Each Letter.

Usually capitalization of each word only harms the comprehension. I like the GitLab guide on this topic, seems very reasonable – https://design.gitlab.com/content/punctuation

**Pull request merged**
