### PR TITLE
[@mantine/core] Removed flex property for Image css

### PR DESCRIPTION
**Pull request by msv96**
### Description:
Removed flex property as it is enabled when the parent uses `display: flex;`.

### Issue:
Screenshot 2024-01-26 131952

### CODE REVIEW

**Comment by rtivital** [comment]
Why it should be removed?

**Comment by msv96** [comment]
Because the parent element has `display: flex;`, the image is not showing since `flex-basis: 0%;`.

**Comment by msv96** [comment]
Or we can make `flex: 1`

**Comment by rtivital** [comment]
It works as intended inside a flexbox container. I do not see any issue with styles on codesandbox – https://codesandbox.io/p/sandbox/cranky-golick-p7t4td?file=%2Fsrc%2FApp.tsx%3A6%2C22

**Comment by msv96** [comment]
Hi @rtivital, found it. When we have `* { min-width: 0px; }`, it behaves like I said earlier. min-width removes the default values for an element and applies min-width - 0px.

https://codesandbox.io/p/sandbox/headless-cookies-6py3mw?file=%2Fsrc%2FApp.tsx%3A16%2C18

Source - https://www.youtube.com/watch?v=cH8VbLM1958

**Comment by rtivital** [comment]
Mantine does not include `* { min-width: 0px; }`, thus this case is not handled by the library.

**Comment by yhranik-vp** [comment]
Hello @rtivital , I'm experiencing the same issue, but only on Firefox.

You can reproduce with the sanbox link you shared.

Chrome
Screenshot 2024-06-06 at 13 35 31

Firefox
Screenshot 2024-06-06 at 13 35 22

**Pull request closed without merging**
