### PR TITLE
[@mantine/dates] Add ability to add presets to mantine DatePickerInput

### PR DESCRIPTION
**Pull request by bastiengrignon**
An implementation of [this discussion](https://github.com/orgs/mantinedev/discussions/5428) with Storybook demos.

I'll be happy to contribute and know if I've done things right or if it's missing something :wink:

### CODE REVIEW

**Comment by rtivital** [comment]
Thanks for showing interest in contributing to Mantine, this feature is planned to be implemented but in a different way.

**Comment by bastiengrignon** [comment]
> Thanks for showing interest in contributing to Mantine, this feature is planned to be implemented but in a different way.

Alright no problem, do you know if this feature is going to be implemented soon ? Or it is not expected in future release for the moment ?

**Comment by rtivital** [comment]
It is not planned to be released in 7.x releases, probably in 8.x

**Comment by bastiengrignon** [comment]
@rtivital I've seen you've released the 8.0 alpha ! I've checked the 8.0 changelog & documentation but didn't find anything implemented yet for this feature ! Do you think this will be available in this release ?

**Comment by rtivital** [comment]
Currently, I do not plan to add this feature to 8.0 release due to the limited capacity.

**Pull request closed without merging**
