### PR TITLE
[@mantine/nprogress] Fix react 18 support

### PR DESCRIPTION
**Pull request by jerebtw**

### CODE REVIEW

**Comment by rtivital** [comment]
@jerebtw can this be merged?

**Comment by jerebtw** [comment]
@rtivital Yes 😄

**Comment by rtivital** [comment]
Thanks!

**Comment by carlesba** [comment]
Is this taking into consideration dependencies that have react as peer dependency?

I'm still getting this warning when using the last mantine-core version:

Screenshot 2022-06-03 at 13 14 30

This should could be solved upgrading the dependencies. Do you know if there's any issue that prevents the upgrade?

**Comment by rtivital** [comment]
This change was never published on npm, react 18 support will be added with version 5.0

**Comment by carlesba** [comment]
Thanks for the info!

**Comment by rtivital** [comment]
It will be released when it is ready, we do not share public roadmap

**Pull request merged**
