### PR TITLE
Fix mouse click for closing modal

### PR DESCRIPTION
**Pull request by MoreBlood**
Modal should not close on right mouse click, on 4/5 buttons and so on

### CODE REVIEW

**Comment by rtivital** [comment]
This will cause some components dropdowns to close modal, for example, MultiSelect dropdown.

**Comment by MoreBlood** [comment]
@rtivital Honestly, I don’t really understand how this is connected, can you give an example? 
Now the name of the prop is misleading that click should be used instead of pressing any mouse button

**Comment by rtivital** [comment]
When MultiSelect dropdown is rendered within portal, all clicks are registered as outside (because its actually outside). But this is unwanted behavior. onMouseDown event is used to solve that issue – you can view Select/MultiSelect code to learn how it is managed.

**Comment by rtivital** [comment]
Fixed by https://github.com/mantinedev/mantine/pull/2669

**Pull request closed without merging**
