### PR TITLE
[@mantine/hooks] use-session-storage: Implement hook.

### PR DESCRIPTION
**Pull request by zhulien-ivanov**
Implementation for: #2169.

Also fixes issue in `useLocalStorage` not supporting falsy values.

### CODE REVIEW

**Review by rtivital — CHANGES_REQUESTED** [review]
We should not duplicate the same logic in two hooks, there should be one hook creator function `createStorage`, it should take single argument `type: 'localStorage' | 'sessionStorage'`. Also, documentation for use-session-storage is obsolete, there is not any difference with use-local-storage, so its docs should be placed in use-local-storage hook with mention that the hook works exactly the same way.

**Comment by zhulien-ivanov** [comment]
Isn't it better if we leave the doc for `useSessionStorage` as a separate page and just present the interface with a reference to `useLocalStorage` and explain that it works the same? Not having a dedicated page for the hook is confusing and leaves the impression that the hook doesn't exist. You can't use the search to find it either.

**Comment by rtivital** [comment]
I doubt that use-session-storage hook will be used frequently, so a separate page that will be exactly the same as use-local-storage hook is not necessary – it will just make maintenance more complicated (it will be required to update two pages when changes are made to shared base).

**Comment by rtivital** [comment]
@zhulien-ivanov please resolve conflicts

**Comment by zhulien-ivanov** [comment]
Done.

**Comment by rtivital** [comment]
I'd better leave it as is and have two separate hooks, it will be easier to maintain.

**Pull request merged**
