### PR TITLE
[@mantine/core]: PinInput component

### PR DESCRIPTION
**Pull request by EmilMalanczak**
I leave it as an mvp version for CR - I'll back to it later 

Missing things:
- docs with demos
- tests

Features:
- copy paste handling
- custom regex validation as prop with predefined numeric / alphanumeric.
- autofocus on/off
- password mask on/off
- onComplete callback which invokes after finishing filling all of the inputs
- amount of inputs controlled via prop
- manageable spacing between inputs and direction - they are wrapper with `Group` component
- custom placeholder as string eg. emoji
- synced with mantine theme styling

Few questions:
- Can I somehow override `paddingRight` of `Input` component without `!important`? 
- On copy-paste is filling from the beginning of PinInput. Should I change it to fill from focused input?
- Is the current behavior of `onComplete` intuitive?

### CODE REVIEW

**Comment by rtivital** [comment]
@EmilMalanczak
- I've changed Input component to set padding-right with emotion instead of inline styles
- *On copy-paste is filling from the beginning of PinInput. Should I change it to fill from focused input?* I think no, we should leave it as is
- *Is the current behavior of onComplete intuitive?* Yes

**Comment by rtivital** [comment]
@EmilMalanczak do you think you will be able to finish it as a part of 3.5 (January 6th)?

**Comment by EmilMalanczak** [comment]
@rtivital I have an issue with styles API tests - atm I commented them. Can you look into it how to make it working as expected? I think It's connected with spreading props on `Group` component. I'm hardly busy recently 😓

**Comment by EmilMalanczak** [comment]
Hmm okay, how should I do it properly?

**Comment by rtivital** [comment]
I've just merge dev branch into next-minor

**Comment by rtivital** [comment]
Please use react testing library to write all new tests

**Comment by rtivital** [comment]
@EmilMalanczak can you finish working on this component? Do you need any help?

**Comment by EmilMalanczak** [comment]
@rtivital sorry for waiting that long fot that, I was way too busy recently

**Comment by rtivital** [comment]
@EmilMalanczak can you please adjust demos and styles api to use new folders structure?

**Comment by EmilMalanczak** [comment]
sure, ill fix that tomorrow

**Comment by rtivital** [comment]
Thanks!

**Pull request merged**
