### PR TITLE
useLocalStorage and useSessionStorage missing dependencies

### LINKED ISSUE #5911: useLocalStorage and useSessionStorage don't reload when key is changed
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.6.2

### What package has an issue?

@mantine/hooks

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

When used a dynamic key and it changes, the value is not re-loaded.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-wk42tp?file=%2Fsrc%2FApp.tsx%3A6%2C2

### Possible fix

[pull](https://github.com/mantinedev/mantine/pull/5910)

### Self-service

- [X] I would be willing to implement a fix for this issue

### PR DESCRIPTION
**Pull request by israelins85**
Fixes #5911

### CODE REVIEW

**Comment by rtivital** [comment]
What real problem do you have that this PR fixes?

**Comment by israelins85** [comment]
When key is changed the value is not loaded.

**Comment by israelins85** [comment]
fixes #5911

**Comment by rtivital** [comment]
Thanks!

**Comment by gl3nn** [comment]
This PR broke all of our usages of it and thus can't update to 7.7.1. Would be nice in the future to show example code on what your issue was and why this would fix it.

**Comment by gl3nn** [comment]
@rtivital @israelins85 This PR broke all of our usages of it and thus can't update to 7.7.1. Would be nice in the future to show example code on what your issue was and why this would fix it.

**Comment by rtivital** [comment]
It would be reverted in next patch

**Comment by israelins85** [comment]
> It would be reverted in next patch

What's happened?

**Comment by israelins85** [comment]
> @rtivital @israelins85 This PR broke all of our usages of it and thus can't update to 7.7.1. Would be nice in the future to show example code on what your issue was and why this would fix it.

https://codesandbox.io/p/sandbox/mantine-react-template-forked-wk42tp?file=%2Fsrc%2FApp.tsx%3A6%2C2

What's broken?

**Comment by israelins85** [comment]
How I say on issue, I use localStorage to store data from many devices key is like `${uuid}/Sensors` and when user changes the current uuid the data of the current need be loaded...

**Comment by israelins85** [comment]
https://github.com/mantinedev/mantine/pull/6019

**Comment by icflorescu** [comment]
@rtivital @israelins85 @gl3nn this also broke [Mantine DataTable](https://icflorescu.github.io/mantine-datatable/) on Mantine 7.7.1, see this issue: https://github.com/icflorescu/mantine-datatable/issues/564 😑

We're using the `useLocalStorage` hook to persist column resizing/ordering state, and it gets triggered infinitely with the same values: 
image

Would be nice to see https://github.com/mantinedev/mantine/pull/6019 pulled...

**Comment by rtivital** [comment]
I've reverted it, the fix will be available in next patch

**Pull request merged**
