### PR TITLE
[@mantine/core] TagInput: re-added to core v6

### PR DESCRIPTION
**Pull request by auronsan1st**
Re-added TagInput v6

-  fixed most bug 
- added variant unstyled 
- added inputFieldPosition props
- change to use rem function
- match style / function mostly with multiselect
- added readOnly props

tested: 

- [x] clearable 
- [x] controlable
- [x] maxTags
- [x] onlyUnique
- [x] readOnly
- [x] validationRegex
- [x] pasteSplit

Screenshot 2023-03-04 at 14 13 08
Screenshot 2023-03-04 at 14 20 39

Screenshot 2023-03-04 at 14 20 49
Screenshot 2023-03-04 at 14 21 02

### CODE REVIEW

**Comment by rtivital** [comment]
It is planned to be merged as a part of 6.1 release

**Comment by UmarFKhawaja** [comment]
> It is planned to be merged as a part of 6.1 release

When is 6.1 planned for release?

**Comment by ar7casper** [comment]
@rtivital Do we have an ETA on 6.1 please?

**Comment by rtivital** [comment]
https://mantine.dev/core/tags-input/

**Pull request closed without merging**
