### PR TITLE
[@mantine/core] MultiSelect: scrollable content

### PR DESCRIPTION
**Pull request by 4m1n83**
This PR aims to add a scrollable behavior to MultiSelect component when a user wants to have a fixed height and width
image

### CODE REVIEW

**Comment by rtivital** [comment]
@4m1n83 can you please resolve conflicts?

**Comment by 4m1n83** [comment]
@rtivital solved conflicts

**Comment by vaynevayne** [comment]
How ingenious. A scroll will be fine.

**Comment by rtivital** [comment]
Thanks for submitting a PR, it is closed because one of these reasons:
- The feature/bug fix  has been implemented in [7.0.0](https://mantine.dev/changelog/7-0-0/)
- The feature is no longer relevant in 7.0.0
- You haven't followed [contribution workflow](https://mantine.dev/contribute/) and did not discuss the feature with a maintainer before submitting the PR

**Pull request closed without merging**
