### PR TITLE
[@mantine/core] Group: Fix position and align for column direction

### LINKED ISSUE #745: Group position styles broken in column layout
### What package has an issue

@mantine/core

### Describe the bug

The Group component does not apply `alignItems` or `justifyContent` props for column groups. Based on the styles it just ignores these props if the group is set to column. Not sure why as they're both completely valid for column mode in flexbox.

### In which browser did the problem occur

Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/amazing-stallman-1vms9?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Remove the conditionals for `direction === 'row'` in `Group.styles.ts`

### PR DESCRIPTION
**Pull request by mattrunyon**
Fixes #745 

alignItems (align) and justifyContent (position) now works properly for both row and column Groups
Added top/bottom as position properties for flex-start and flex-end
Adjusted demo so it better shows the effects of the properties

### CODE REVIEW

**Comment by mattrunyon** [comment]
@rtivital Which branch should this target and I can rebase/fix merge conflicts

**Comment by rtivital** [comment]
It should be targeted for master

**Comment by mattrunyon** [comment]
Ok it has been rebased to target master and fixed merge conflict

**Comment by mattrunyon** [comment]
@rtivital Fixed merge conflicts w/ 4.0

**Comment by rtivital** [comment]
Thanks!

**Pull request merged**
