### PR TITLE
Refactoring building scripts.

### LINKED ISSUE #79: Cannot work with vitejs.
I'am using mantine in vitejs. But it's not work.

image

The source code is here. https://github.com/blackcater/vitejs-with-mantine.bug-report

### PR DESCRIPTION
**Pull request by blackcater**
## Changes

- [x] Use `rollup` instead of `webpack`.
- [x] Use `esno` instead of `ts-node`.
- [x] Refactor build script:

```shell
$ esno scripts/build --help
选项：
  --help       显示帮助信息                                               [布尔]
  --version    显示版本号                                                 [布尔]
  --all        Build all packages.                        [布尔] [默认值: false]
  --project    Specify package should be bundled.                       [字符串]
  --analyze    Generate analyze files.                    [布尔] [默认值: false]
  --sourcemap  Generate sourcemap.                         [布尔] [默认值: true]
  --minify     Minify umd files.                          [布尔] [默认值: false]
  --formats    Specify module code generation: 'es', 'cjs', 'umd'.
                [数组] [可选值: "es", "cjs", "umd"] [默认值: ["es","cjs","umd"]]

示例：
  build all --formats umd cjs   Building only umd and cjs packages.
  build mantine-core --analyze  Building mantine-core package and generating
                                analyzing file.
```

- [x] Refactor release script, support prerelease:

```
选项：
  --help                显示帮助信息                                      [布尔]
  --version             显示版本号                                        [布尔]
  --stage               Prerelease stage: 'alpha', 'beta' or 'rc'
                                        [字符串] [可选值: "alpha", "beta", "rc"]
  --tag                 Tag                          [字符串] [默认值: "latest"]
  --skip-version-check  Skip checking version.            [布尔] [默认值: false]
  --skip-build          Skip building step.               [布尔] [默认值: false]
  --skip-publish        Skip publishing step.             [布尔] [默认值: false]

示例：
  release minor --skip-build  Release but skip building packages.
  release minor --alpha       Prerelease to alpha stage.
```

- [x] Update dependencies to latest version, except `storybook`.

## Checklist

- [x] All unit test passed.
- [x] All npm scripts works well.
- [x] Storybook works well.
- [x] Docs(Gatsby website) works well.
- [x] Build script works well.
- [x] Release script works well.

## Suggestions

This PR is huge, I cannot guarantee that it will works well for every situation like before. So I think this changes should be prerelease before checking everything works well.

### How to prerelease?

``` shell
# v1.1.1 -> v1.2.0-alpha.0
> npm run _release minor --stage alpha --tag next

# v1.2.0-alpha.0 -> v1.2.0-alpha.1
> npm run _release minor --stage alpha --tag next

# v1.2.0-alpha.1 -> v1.2.0-beta.0
> npm run _release minor --stage beta --tag next

# v1.2.0-beta.0 -> v1.2.0-rc.0
> npm run _release minor --stage rc --tag next

# everything works well
# v1.2.0-rc.0 -> v1.2.0
> npm run _release minor
```

Closes #79

### CODE REVIEW

**Comment by rtivital** [comment]
Hi Elon, thanks for your huge work, I really appreciate your help with this project, I've checked all scripts and everything works fine.

I've got several questions:
- Build script outputs that source maps are not valid, am I doing something wrong? Is there a way to fix that
Снимок экрана 2021-05-21 в 16 28 36

- Storybook reports that some babel configuration in missing, is it something that can be easily fixed?

```
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-property-in-object since the "loose" mode option was set to "true" for @babel/plugin-proposal-private-methods.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
	["@babel/plugin-proposal-private-property-in-object", { "loose": true }]
to the "plugins" section of your Babel config.
```

**Comment by rtivital** [comment]
I've published 1.2.0-alpha.3 version of all packages, does not seem to work, we have 2 different types of packages:
- public – @mantine/core, @mantine/hooks, @mantine/notifications, @mantine/tag-picker
- private – @mantine/utils, @mantine/theme – these packages are exported from @mantine/core and are not published to npm registry

Currently It does not seem to work and tries to resolve @mantine/utils and @mantine/theme packages from node_modules

**Comment by rtivital** [comment]
I've made some adjustments to package.json to correctly handle @mantine/theme and @mantine/utils – https://github.com/mantinedev/mantine/tree/feature/fix-vitejs-validation

**Comment by blackcater** [comment]
> Hi Elon, thanks for your huge work, I really appreciate your help with this project, I've checked all scripts and everything works fine.
> 
> I've got several questions:
> 
> * Build script outputs that source maps are not valid, am I doing something wrong? Is there a way to fix that
> 
> Снимок экрана 2021-05-21 в 16 28 36
> 
> * ~Storybook reports that some babel configuration in missing, is it something that can be easily fixed?~ (not related to this PR)
> * Is there some reason why `.nvm` file was removed?

### Build script outputs that source maps are not valid, am I doing something wrong?

> I fixed it. https://github.com/mantinedev/mantine/pull/90/commits/ee6af6590306f6e410f16dee6d7a6279b3b3af96

###  Storybook reports that some babel configuration in missing, is it something that can be easily fixed?

> I change storybook's version to `^6.1.11`, so `6.2.9` will matched. And storybook@6.2.9 has some problems.
>
> https://github.com/storybookjs/storybook/issues/14805
> https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-default-postcss-plugins
>
> I fixed it. https://github.com/mantinedev/mantine/pull/90/commits/1be42709cc51146bb6c37bd13c26f803fb5e8be8

### Is there some reason why .nvm file was removed?

> It's my fault. I forgot to add it back.

**Comment by blackcater** [comment]
> I've made some adjustments to package.json to correctly handle @mantine/theme and @mantine/utils – [https://github.com/mantinedev/mantine/tree/feature/fix-vitejs-validation](https://github.com/mantinedev/mantine/tree/feature/fix-vitejs-validation?rgh-link-date=2021-05-21T17%3A22%3A19Z)
> 
> I guess the easy fix will be to add exclude to rollup configuration:
> 
> ```
> externals({
>   exclude: ['@mantine/utils', '@mantine/theme']
> })
> ```
> 
> I'll try out this tomorrow

- `@mantine/utils` is used by `@mantine/hooks` and `@mantine/core`, they are public. So if we don't publish `@mantine/utils`, then we should bundle `@mantine/utils` into `@mantine/hooks` and `@mantine/core`.
- `@mantine/types` is used by `@mantine/theme`, `@mantine/theme` is used by `@mantine/core`. So If we don't publish `@mantine/theme`, then we should bundle `@mantine/theme` into `@mantine/core`.

So I deliberately remove `private: true` in `@mantine/utils`, `@mantine/types` and `@mantine/theme` packages.

**Comment by rtivital** [comment]
Alright, I'll then merge @mantine/theme into @mantine/core and @mantine/utils to @mantine/hooks, thanks again for your help!

**Comment by rtivital** [comment]
Just published 1.2.0-alpha.5 with merged packages, works fine with next.js and your [vite](https://github.com/blackcater/vitejs-with-mantine.bug-report) example

**Pull request merged**
