### PR TITLE
[@mantine/core] MultiSelect: Fix search input width

### PR DESCRIPTION
**Pull request by PegasisForever**
Related: #1211

### CODE REVIEW

**Comment by rtivital** [comment]
Are you sure it will fix it? I haven't checked, but input has width: 60

**Comment by PegasisForever** [comment]
Which example are you using? I checked it on storybook and its working great.

**Comment by PegasisForever** [comment]
Oh i should prabably remove the width line since it is redundent now

**Comment by rtivital** [comment]
I guess it should be min-width instead.

**Comment by rtivital** [comment]
Thanks!

**Pull request merged**
