### PR TITLE
[@mantine/core] Title: Fix `inline` prop being ignored

### LINKED ISSUE #2180: Title component does not respect inline=true
### What package has an issue

@mantine/core

### Describe the bug

A `<Title inline>` element does not set `line-height` to 1 because the property is defined twice.
grafik

### What version of @mantine/hooks page do you have in package.json?

5.2.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/optimistic-architecture-vj6t9f

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Amend [getLineHeight](https://github.com/mantinedev/mantine/blob/557d7728ccebfe2b15cf38ec2095efe83d81118c/src/mantine-core/src/Title/Title.styles.ts#L20) to return 1 if inline is set to true.

### PR DESCRIPTION
**Pull request by Narcha**
Fixes #2180

### CODE REVIEW

**Comment by Narcha** [comment]
To test this, I added an example to the storybook [here](https://github.com/mantinedev/mantine/blob/0326f9b75525a1acebaf69ae569c7b4b394a6fd3/src/mantine-core/src/Title/Title.story.tsx#L48-L62):
grafik
Should I push that as well?

**Comment by Narcha** [comment]
Please also let me know if my solution doesn't fit your code style, there are many other ways to fix this.

**Comment by rtivital** [comment]
Great job, thanks!

**Comment by Narcha** [comment]
Thanks for making Mantine, it's a joy to work with :smile:

**Pull request merged**
