### PR TITLE
Fix: DateInput does not default to minDate month

### LINKED ISSUE #5695: The minDate in Dates should be the default date, when date is not given
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.5.1

### What package has an issue?

@mantine/dates

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

When the DateInput property (minDate) is set to, for example, 2024-09-01, and the DateInput is controlled through the form but the date is undefined, I expect the calendar to automatically navigate to the correct month of the minDate. It can be confusing for the user when the min date is in the future (and the month is greyed out). Additionally, the defaultDate does not work properly when using the mantine/forms plugin.

### If possible, include a link to a codesandbox with a minimal reproduction

_No response_

### Possible fix

Start the default month (date) with the minDate given.

### Self-service

- [ ] I would be willing to implement a fix for this issue

### PR DESCRIPTION
**Pull request by michaelperros**
Fixes #5695 

If you need any adjustments, please let me know. Happy to revise based on your feedback.

Thanks

### CODE REVIEW

**Comment by michaelperros** [comment]
Sorry this has failed checks. I will revise and update

**Comment by michaelperros** [comment]
Checks passed! Let me know if you need anything else here.

Additionally, I wanted to note that I found a separate bug in both the master and my pr. The bug is that when minDate is set, the selectable days in the DateInput Calendar start one day before the minDate. The expected behavior is that the selectable days would start on the minDate. Since it's happening in the master and is not directly related to my pr or this issue, I did not fix it here. I will create a new issue shortly to address it.

**Comment by rtivital** [comment]
I'd prefer this logic to be a little different to avoid accidental breaking changes. It should check whether the minDate is after the current date and only if it is, use it as the default date.

**Comment by michaelperros** [comment]
Good call. Code has been update. Let me know if any further tweaks are needed. Thanks

**Comment by rtivital** [comment]
Thanks!

**Pull request merged**
