### PR TITLE
[docs] Adding more content to nextjs _document

### PR DESCRIPTION
**Pull request by maks112v**
Adding docs to prevent confusion when working with nextjs.

Solves: https://github.com/mantinedev/mantine/issues/1246

### CODE REVIEW

**Comment by rtivital** [comment]
Does these changes fix your issue?

**Comment by maks112v** [comment]
Yep the deployment works perfectly. I copied the _document without looking up nextjs docs and it worked on development but not production so thought I would fix the docs to prevent farther confusion.

**Comment by rtivital** [comment]
Okay, thanks! I'll review that and add to the docs

**Comment by rtivital** [comment]
Thanks!

**Pull request merged**
