### PR TITLE
[@mantine/hooks] use-did-update: Add tests

### PR DESCRIPTION
**Pull request by mctessi**
I wrote another simple test (test coverage cannot be too high :)  !

### CODE REVIEW

**Comment by rtivital** [comment]
So, are you planning to close this PR after I review it like a previous one?

**Comment by rtivital** [comment]
Yep, your previous PR is gone – https://github.com/mantinedev/mantine/pull/1119

**Comment by rtivital** [comment]
yes

**Comment by mctessi** [comment]
Pardon my stupid mistakes! It seems, that use-click-outside tests are also included in this PR!? I promise to be more cautious with pushes from my local to the origin repo...

**Comment by mctessi** [comment]
I have not expected, that every push would be included in this PR! Should I try to remove these commits?

**Comment by rtivital** [comment]
Thanks!

**Pull request merged**
