### PR TITLE
types: make createStyle go to original definition

### PR DESCRIPTION
**Pull request by imranbarbhuiya**
By making this change, a user can click on the className to go to the original definition. Like clicking on `classes.wrapper`, it'll go to the object where `wrapper` was defined. Also renaming `wrapper` will rename it from all the places

### CODE REVIEW

**Comment by rtivital** [comment]
@imranbarbhuiya please fix failing tests

**Comment by imranbarbhuiya** [comment]
I wasn't at home so did it from phone 😂 I'll fix the formatting once I open my laptop.

**Comment by rtivital** [comment]
@imranbarbhuiya please fix failing tests

**Comment by imranbarbhuiya** [comment]
Hi, I think my ide was merging this prettier config with the default one. I formatted from cli now can u run the workflow again please?

**Comment by rtivital** [comment]
It does not work, example with `Accordion.Panel` component after and before your changes
Снимок экрана 2022-12-05 в 20 17 26
Снимок экрана 2022-12-05 в 20 17 48

**Comment by imranbarbhuiya** [comment]
It might be due to the last change I did which I didn't tested. I'll test everything and will inform you.

**Comment by imranbarbhuiya** [comment]
The `extends` was causing the issue. Now to fix it, I had to use the `generic` and an `assertion` too. But if u don't like the assertion, lmk I'll try to make it work with a simpler solution without breaking existing typings

**Comment by rtivital** [comment]
It works now, thanks!

**Pull request merged**
