### PR TITLE
[docs] Form: Document UseFormReturnType properties

### PR DESCRIPTION
**Pull request by Alf-Melmac**
This PR documents the properties returned by the use-form hook. I've also added the missing properties `validateInputOnChange` and `isValid` and renamed the wrongly name `resetTouched` and `resetDirty` functions on the overview page.

As discussed in https://discord.com/channels/854810300876062770/1010677442656075876

### CODE REVIEW

**Comment by rtivital** [comment]
It should be called "API reference". It also should be a part of use-form.mdx, no need for separate page

**Comment by rtivital** [comment]
@Alf-Melmac when will you finish this PR, so that I'm able to review it?

**Comment by Alf-Melmac** [comment]
I resolved the todo yesterday, i think you can start

**Comment by rtivital** [comment]
@Alf-Melmac please resolve conflicts

**Comment by rtivital** [comment]
Thanks!

**Pull request merged**
