### PR TITLE
[@mantine/core] Indicator: count support

### PR DESCRIPTION
**Pull request by AmelloAster**
This pr I did two things in total
The first one.
Enrich the functionality of Indicator
1.  Digital overflow display
2.  Digital animation
3. `processing` animation
4. `showZero` control
5. `disabled` => `isShow`
For the fifth point, I think the name `disabled` will bring misunderstanding, `disabled` usually means the component is `disabled`, but it is still displayed, while this time is to control whether the component is displayed or not, so I think `isShow` is more appropriate
The second piece: enrich is function
I encapsulated an is function file, which contains many basic type determination functions, and I think there will be related needs in the subsequent development

Indicator-related docs and demos have been added, and unit tests for the is function have been passed.
image
image

### CODE REVIEW

**Comment by rtivital** [comment]
Hi @AmelloAster, thanks for a PR, please change `isShow` to `disabled` back to merge it – it is a breaking change and we cannot introduce it in minor release.

**Comment by AmelloAster** [comment]
> 嗨，@AmelloAster，感谢您的PR，请更改以将其合并 - 这是一个重大更改，我们不能在次要版本中引入它。`isShow``disabled`
ok

**Comment by AmelloAster** [comment]
> Hi @AmelloAster, thanks for a PR, please change `isShow` to `disabled` back to merge it – it is a breaking change and we cannot introduce it in minor release.

I've finished changing

**Comment by rtivital** [comment]
@AmelloAster can you please resolve conflicts?

**Comment by AmelloAster** [comment]
> @AmelloAster can you please resolve conflicts?

OK

**Comment by rtivital** [comment]
Thanks!

**Pull request merged**
