### PR TITLE
Fix #782: [@mantine/hooks] Interval start create ref if not active already

### LINKED ISSUE #782: [@mantine/hooks] Interval Hook start() creates unbounded intervals
### What package has an issue

@mantine/hooks

### Describe the bug

If you call `interval.start()` X times it starts X timers but calling stop can only stop the latest one.

### In which browser did the problem occur

ALL

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/sharp-matan-zx040?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

PR being submitted with...

```typescript
  const start = () => {
    if (!active) {
       setActive(true);
       intervalRef.current = window.setInterval(fn, interval);
    }
  };
```

### PR DESCRIPTION
**Pull request by melloware**

### CODE REVIEW

**Comment by rtivital** [comment]
Please fix ci errors to merge this PR

**Comment by melloware** [comment]
I couldn't tell what the CI errors were they looked unrelated to my change?

**Comment by rtivital** [comment]
```
> mantine@3.6.4 test
> npm run prettier:test && npm run syncpack && npm run typecheck && npm run lint && npm run jest


> mantine@3.6.4 prettier:test
> prettier --check "**/*.{ts,tsx}"

Checking formatting...
[warn] src/mantine-hooks/src/use-interval/use-interval.ts
[warn] Code style issues found in the above file(s). Forgot to run Prettier?
Error: Process completed with exit code 1.
```

CI says that there are some issues with prettier

**Comment by melloware** [comment]
Got it will fix.

**Comment by melloware** [comment]
OK change committed if you want to run the workflow.

**Comment by melloware** [comment]
All passed!

**Comment by rtivital** [comment]
Thanks!

**Pull request merged**
