### PR TITLE
add other size to type Contianer Component css varibales

### PR DESCRIPTION
**Pull request by mehdiraized**
we need change other size in createTheme > components > Container
after change size i see we have problem in typescript

### CODE REVIEW

**Comment by rtivital** [comment]
You can find documentation on how to change size here – https://mantine.dev/styles/variants-sizes/#sizes-with-components-css-variables

**Comment by mehdiraized** [comment]
i have issue
```
Type '() => { root: { '--container-size-xs': string; '--container-size-sm': string; '--container-size-md': string; '--container-size-lg': string; '--container-size-xl': string; }; }' is not assignable to type 'PartialVarsResolver<{ props: ContainerProps; ref: HTMLDivElement; stylesNames: "root"; vars: ContainerCssVariables; }>'.
  Call signature return types '{ root: { '--container-size-xs': string; '--container-size-sm': string; '--container-size-md': string; '--container-size-lg': string; '--container-size-xl': string; }; }' and 'PartialTransformVars<ContainerCssVariables>' are incompatible.
    The types of 'root' are incompatible between these types.
      Type '{ '--container-size-xs': string; '--container-size-sm': string; '--container-size-md': string; '--container-size-lg': string; '--container-size-xl': string; }' has no properties in common with type 'Partial<Record<"--container-size", string | undefined>>'.
 ```
 
Code:
```
'use client';

import { Container, createTheme } from '@mantine/core';

export const theme = createTheme({
	fontFamily: 'Optimistic Display',
	breakpoints: {
		xs: '30em',
		sm: '60em',
		md: '74em',
		lg: '82em',
		xl: '90em',
	},
	components: {
		Container: Container.extend({
			vars: () => ({
				root: {
					'--container-size-xs': 'calc(30em*var(--mantine-scale))',
					'--container-size-sm': 'calc(60em*var(--mantine-scale))',
					'--container-size-md': 'calc(74em*var(--mantine-scale))',
					'--container-size-lg': 'calc(82em*var(--mantine-scale))',
					'--container-size-xl': 'calc(90em*var(--mantine-scale))',
				},
			}),
		}),
	},
});
```

**Comment by rtivital** [comment]
The issue reported by TypeScript is correct, with CSS variables resolver you are supposed to resolve these values with given component props as shown in example. If you want to add static styles, you should use `classNames` prop instead.

**Comment by mehdiraized** [comment]
> The issue reported by TypeScript is correct, with CSS variables resolver you are supposed to resolve these values with given component props as shown in example. If you want to add static styles, you should use `classNames` prop instead.

Can you write an example for this piece of code?

**Comment by rtivital** [comment]
https://codesandbox.io/s/cool-darkness-yctpdx?file=/src/App.tsx

**Comment by mehdiraized** [comment]
> https://codesandbox.io/s/cool-darkness-yctpdx?file=/src/App.tsx

i have problem without size props container component
i need change default sizes container

```
      <Container bg="gray">
        without size props container
      </Container>
```

**Comment by rtivital** [comment]
I've updated the sandbox to include container without size.

**Comment by mehdiraized** [comment]
> I've updated the sandbox to include container without size.

Without the size of the page, the container does not change the size of the various displays

**Comment by rtivital** [comment]
https://mantine.dev/core/container/#responsive-max-width

**Pull request closed without merging**
