### PR TITLE
[@mantine/core] Fix: not applied bd style prop

### PR DESCRIPTION
**Pull request by ryuhangyeong**
## Description

After installing `7.10.0`, it does not work properly when using `bd` Style props.

## Example

```tsx
export function Usage() {
  return (
    <div style={{ padding: 40 }}>
      <Text bd={`1px solid ${'#333'}`}>Just text</Text>
    </div>
  );
}
```

## Before

image

## After

image

### CODE REVIEW

**Comment by crosskayla** [comment]
Thank you 💯 Updated for this feature and would love to see it working

**Comment by rtivital** [comment]
Thanks!

**Comment by ryuhangyeong** [comment]
@rtivital 

According to my use case, I think I also need a style prop like below. 🤔

- `bdt` (border-top)
- `bdr` (border-right)
- `bdl` (border-left)
- `bdb` (border-bottom)

May I suggest an MR that adds that attribute?

**Comment by ryuhangyeong** [comment]
Thank you for answer

**Pull request merged**
