### PR TITLE
Pr/multiselect selected

### PR DESCRIPTION
**Pull request by jsheely**
Allow for multi-select options not to be removed from the list when selected. Gives opportunity for toggling selected state of options from the list

**TODO**
- [x] Need to add unit tests for this scenario
- [x] It would be nice if there was a default style applied for selected state when this flag is enabled
- [x] Discuss with maintainer the MultiSelect prop name for `disableSelectedItemFiltering` if it matches project naming. I found `disableToolTips` and `disableOutsideEvents` which feels similar

image

```javascript
<MultiSelect
  label="Your favorite Rick and Morty character"
  placeholder="Pick all that you like"
  itemComponent={({ selected, value, ...rest }: SelectItem) => (
    <div {...rest} style={selected ? { backgroundColor: 'blue' } : null}>
      {value}
    </div>
  )}
  disableSelectedItemFiltering
  data={[
    { value: 'rick', label: 'Rick', group: 'Used to be a pickle' },
    { value: 'morty', label: 'Morty', group: '' },
    { value: 'beth', label: 'Beth', group: 'Never was a pickle' },
    { value: 'summer', label: 'Summer', group: 'Never was a pickle' },
  ]}
/>
```

### CODE REVIEW

**Comment by jsheely** [comment]
`[data-selected]` is actually already styled by default. Likely for the single select dropdown

**Comment by jsheely** [comment]
@rtivital Let me know what you think of `disableSelectedItemFiltering` as an interface property name.

**Comment by jsheely** [comment]
@rtivital Any feedback on why you closed this PR?

I can add some more information around the usefulness of this scenario. Or did it just get nuked because the dev branch got nuked?

**Comment by rtivital** [comment]
Yep, I've accidentally deleted the dev branch and it seems that the PR got closed automatically

**Comment by rtivital** [comment]
Should be fine now

**Comment by Valar103769** [comment]
how is it going?

**Comment by rtivital** [comment]
Thanks!

**Comment by Valar103769** [comment]
maxTagCount is ready for the calendar

**Pull request merged**
