### PR TITLE
Migration to @mantine/styles from react-jss

### PR DESCRIPTION
**Pull request by rtivital**

### CODE REVIEW

**Comment by rtivital** [comment]
@EmilMalanczak @achmurali would you please have a look and try things out, maybe you would be able to see some broken styles that I've missed

**Comment by achmurali** [comment]
> @EmilMalanczak @achmurali would you please have a look and try things out, maybe you would be able to see some broken styles that I've missed

Yeah definitely @rtivital . So, I thought I could go over the storybooks of the components and maybe tryout some demos.
Any other ideas are welcome 😅.
 
First thing I noticed is in the docs, the jumbotron isn't centered. Was it deliberate?
image

**Comment by rtivital** [comment]
Yep, I'll be rebuilding home page to be more clear

**Comment by EmilMalanczak** [comment]
I will dig into it tonight. 

Backing to the docs page, I've found that lib some time ago and I think it would be good to use that trick mentioned there for gatsby / next [link](https://github.com/donavon/use-dark-mode#that-flash). 
As I see there is a gatsby plugin for it. I'm highly into dark mode preference and almost every time I open docs I get light mode flash at first render

**Comment by dukesx** [comment]
I see good things @rtivital 👍 , i suppose emotion was, is and should be the next level of CSS in JSS 😄

**Comment by rtivital** [comment]
Well, I've found a good way to implement it without changing the whole project structure, so yes, it's much better now

**Comment by dukesx** [comment]
I am sure that this transition will attract more PRs too, since emotion is alot more loved and easier to use too.

**Pull request merged**
