### PR TITLE
[@mantine/dropzone] MIME TYPE: Swap xlsx and xls for MS_EXCEL_MIME_TYPE – Change in @mantine/dropzone package at mime-types.ts file

### PR DESCRIPTION
**Pull request by micro9000**
Change in @mantine/dropzone package at mime-types.ts file

### CODE REVIEW

**Comment by rtivital** [comment]
why?

**Comment by micro9000** [comment]
Hi, sorry I forgot to include this on my description: https://github.com/mantinedev/mantine/issues/2615#issue-1394360844

**Comment by micro9000** [comment]
There's no impact on the UI but the first option in the file browser will always Microsoft Excel 97-2003 which is an old one and most of the users now are using the new version (xlsx), so it's better to show all xlsx files by default instead of xls

I don't have the right example but I'm referring to, is the drop down menu of the the file browser.
image

**Comment by micro9000** [comment]
Hey,

**Pull request closed without merging**
