### PR TITLE
[@mantine/carousel] Carousel: add options `skipSnaps` and `containScroll`

### PR DESCRIPTION
**Pull request by italodeandra**
Current workaround is to reinit embla instance.

```ts
const [embla, setEmbla] = useState<Embla | null>(null);
useEffect(() => {
  if (embla) {
    embla.reInit({ containScroll: "trimSnaps", skipSnaps: true });
  }
}, [embla]);
```

So to me it seems reasonable to add it directly to Mantine.

### CODE REVIEW

**Comment by italodeandra** [comment]
Not sure what this error from the workflow means:

```
FAIL src/mantine-carousel/src/Carousel.test.tsx
  ● Console

    console.error
      Error: Uncaught [TypeError: Cannot read property 'left' of undefined]
```

I didn't really change anything on the Carousel itself so it would break on the test?

**Comment by rtivital** [comment]
It may have broken something in embla integration, you can run tests locally with `npr jest src/mantine-carousel` command

**Comment by italodeandra** [comment]
> It may have broken something in embla integration

But I just added the possibility to add two properties without changing the test, so if those properties aren't being used, the test shouldn't break. Weird. 

Does the test do something automatically that I don't have control of? I'll check it later.

**Comment by italodeandra** [comment]
After some investigations, I discovered that this error happens when you try to load the option `containScroll: "trimSnaps"` but without any slides (empty). I'll fix it.

**Comment by rtivital** [comment]
@italodeandra any progress on this?

**Comment by italodeandra** [comment]
@rtivital 

Just pushed the fix for the property, by using the right default values. 

Loading an empty carousel with the `containScroll: "trimSnaps"` is a separate issue that I don't think should be fixed on the library level. What do you think?

**Comment by rtivital** [comment]
It is managed by embla, should be fine.

**Comment by rtivital** [comment]
Thanks!

**Pull request merged**
