### PR TITLE
feat: adds flip component

### PR DESCRIPTION
**Pull request by gfazioli**
@rtivital Hello,

First of all, I would like to thank you for the excellent library you have developed. Not only is it very useful, but I believe it is written very well and has inspired me during development 👍 
I have been using it for an internal project for a long time, especially version 6. I can't wait to plan a migration to version 7 in 2024.

While using it, I have written a component built on top of Mantine, which has been very helpful to me. So I thought of proposing this pull request where you will find a draft of a Flip component. It's really useful for managing a dual UI, for example, like a Mac OS widget.
Unfortunately, I didn't have the time to discuss it earlier and polish the code/docs like you do, but let me know what you think.

image

### CODE REVIEW

**Comment by pedrocarlos-ti** [comment]
Nice job @gfazioli  👏🏻 

Hope to see your component in the next version of Mantine 🎉

**Review by soham2k06 — APPROVED** [review]
Well done, master.
It helps to make components rtl.

**Comment by rtivital** [comment]
Thanks for showing interest in contributing to Mantine! Currently, I do not have the capacity to maintain this component in the library. You are welcome to publish a separate package that implements this component as a separate extension. In future releases, there will be a separate section on mantine.dev website for community extensions. If you want to get started with a template, you can use mantine-extension-template – https://github.com/mantinedev/extension-template

**Comment by gfazioli** [comment]
@rtivital Thank you for notifying me about the template. I have prepared everything and it seems to be working. The only issue is that even though I am logged into `npm`, where I have already released other packages, when trying with your template, it gives me an authentication error. Do you happen to have any ideas on how to resolve it?
image

**Comment by rtivital** [comment]
You need to login with yarn first – https://yarnpkg.com/cli/npm/login
Authentication state is not shared between yarn and npm

**Comment by gfazioli** [comment]
@rtivital yep, I was able to fix it with

```
yarn npm login --publish
```

and now it looks like a missing field

image

**Comment by gfazioli** [comment]
@rtivital component published

- [Repo](https://github.com/gfazioli/mantine-flip)
- [Docs](https://gfazioli.github.io/mantine-flip/)

**Pull request closed without merging**
