### PR TITLE
[@mantine/dates] TimeInput: Add `format` and `clearable` prop

### PR DESCRIPTION
**Pull request by jerebtw**
Fix for https://github.com/mantinedev/mantine/issues/581 and https://github.com/mantinedev/mantine/issues/580

### CODE REVIEW

**Comment by rtivital** [comment]
Thanks for a PR! Select does not feel right in this case. It should be replaced with a regular input like every other field withing time inputs:
- When user presses up/down arrows on this field, it switches between am/pm
- When user types letter `a`, it switches to am (in case of range input: focus should be moved to next range hours field)
- When user types letter `p`, it switches to pm (in case of range input: focus should be moved to next range hours field) 
- When user finishes entering last number field (minutes or seconds) am/pm field should be focused
- Icon near am/pm should be removed

Currently, the flow of entering range is broken – there is not a good way to enter time in 12h format with just keyboard:

https://user-images.githubusercontent.com/10353856/147450732-2d5ac355-d7cf-440f-9694-9f5791702a34.mov

**Comment by jerebtw** [comment]
Okay I will work on it. (NativeSelect would probably also work)

**Comment by rtivital** [comment]
Yeah, maybe select will work for that, just don't use NativeSelect for that, it does not have any useful styles or features, `select` html element will work better in this case

**Comment by jerebtw** [comment]
I corrected the keyboard flow and changed the component from Select to NativeSelect because NativeSelect was easier for me to work with. My problem is when I use the variant of NativeSelect the options also have no style. So when you are in dark mode it looks really bad. (see image)

image

**Comment by rtivital** [comment]
Select element does not feel right either when working with keyboard only – there is no indication that it is focused, and it is not clear what the user should do to select it. I guess there is no other option rather than using regular text input for this like I've described in the first comment. 

https://user-images.githubusercontent.com/10353856/147537183-2e5d789a-59fa-415a-a5d3-64561fb3f5c4.mov

**Comment by jerebtw** [comment]
@rtivital can you please check this. Thanks

**Comment by rtivital** [comment]
@jerebtw can you please resolve conflicts?

**Comment by jerebtw** [comment]
I resolved the conflicts and fix the code

**Comment by jerebtw** [comment]
@rtivital is this new hook okay? (https://github.com/mantinedev/mantine/pull/586/commits/f995808a1246a47707f2be26d3b063cb06229ae0)

**Comment by jerebtw** [comment]
Cleanup version: https://github.com/mantinedev/mantine/pull/607

**Pull request closed without merging**
