### PR TITLE
Autocomplete migration

### PR DESCRIPTION
**Pull request by achmurali**
This PR fixes -
- Nothing Label on zero results for autocomplete.
- Migration to Autocomplete in Navbar for search functionality.

### CODE REVIEW

**Comment by rtivital** [comment]
Thanks for PR! Code looks great and can be merged, but I'll need to review the UI first in about 2 days

**Comment by achmurali** [comment]
Hey @rtivital,

The search bar has one problem, on submitting I am not able to clear the input query. Any inputs would be helpful.

**Comment by rtivital** [comment]
Have your tried calling `handleQueryChange` with empty string on submit?

**Comment by achmurali** [comment]
> Have your tried calling `handleQueryChange` with empty string on submit?

I believe I do the similar thing in handleSubmit.

**Comment by achmurali** [comment]
Hi @rtivital,

was able to fix the issue of clearing the input on submit, had to correct the invocation of onchange and onsubmit calls.

Thanks

**Comment by rtivital** [comment]
@achmurali thanks for pull request, it's a really outstanding work! Everything works perfect

**Pull request merged**
