### PR TITLE
[@mantine/form] Add superstruct support

### PR DESCRIPTION
**Pull request by dmshvetsov**
add superstructResolver for useForm validation

## links

- [superstruct](https://github.com/ianstormtaylor/superstruct)

### CODE REVIEW

**Comment by dmshvetsov** [comment]
@rtivital looks like you prefer to avoid adding peer dependencies of validation libraries. That is why I decided to use `any` instead of the schema type. Nevertheless, it will be nice to have a `Struc` type from "superstruct" in place on `any` for better type safety. Keen to know your perspective on this.

Do you need help with writing docs for the useForm + supersturct integration?

**Comment by rtivital** [comment]
Please include documentation, should be the same as for other resolvers

**Comment by dmshvetsov** [comment]
@rtivital docs added, please take another look when you have a chance

**Comment by rtivital** [comment]
Thanks!

**Pull request merged**
