### PR TITLE
[@mantine/core] AspectRation: init

### PR DESCRIPTION
**Pull request by achmurali**
This PR implements AspectRation component.

For the padding hack followed the doc - https://keithjgrant.com/posts/2017/03/aspect-ratios/

### CODE REVIEW

**Comment by Ultra-Instinct-05** [comment]
I guess this should be `AspectRatio` and not `AspectRation` ?

**Comment by achmurali** [comment]
> I guess this should be `AspectRatio` and not `AspectRation` ?

I guess, vitaly would be able to answer. I was suggested to name as such.

**Comment by rtivital** [comment]
Yep @achmurali it should be named as AspectRatio, sorry it was a typo

**Comment by rtivital** [comment]
@achmurali can you please adjust demos and styles api to use new folders structure?

**Comment by rtivital** [comment]
Thanks!

**Pull request merged**
