### PR TITLE
[@mantine/core] NumberInput: Fix precision parser behavior when the value is nullable

### PR DESCRIPTION
**Pull request by mlshvdv**

### CODE REVIEW

**Comment by rtivital** [comment]
NumberInput value cannot be null, the library does not support it. It is explicitly defined in component props type – value can either be an empty string or number.

**Comment by mlshvdv** [comment]
@rtivital Yeah, but sometimes it's difficult to control nullable values which passed to the mantine/form's initialValues. So, I think it will be better to have a fix for the precision parser, to avoid the error of the toFixed() method. 

```js
if (val === '' || value === null) return '';

let result = val.toFixed(precision);
```
instead of:

https://github.com/mantinedev/mantine/blob/d03cb692eedd7e525275bdedcc9b077b141f0b78/src/mantine-core/src/NumberInput/NumberInput.tsx#L175-L177

**Comment by mlshvdv** [comment]
@rtivital  This fix helps to avoid this bug when using mantine forms:

Screenshot 2023-07-08 at 13 22 48

**Comment by rtivital** [comment]
Thanks for submitting a PR, it is closed because one of these reasons:
- The feature/bug fix  has been implemented in [7.0.0](https://mantine.dev/changelog/7-0-0/)
- The feature is no longer relevant in 7.0.0
- You haven't followed [contribution workflow](https://mantine.dev/contribute/) and did not discuss the feature with a maintainer before submitting the PR

**Pull request closed without merging**
