### PR TITLE
[@mantine/hooks] use-did-update: Optimize fast refresh

### PR DESCRIPTION
**Pull request by u3u**

### CODE REVIEW

**Comment by rtivital** [comment]
Why are these changes required?

**Comment by u3u** [comment]
At development time HMR will uninstall the component, but `mounted` is not reset, after that every save refresh will trigger `useDidUpdate`, sorry I didn't pay attention to ESLint

**Comment by rtivital** [comment]
@u3u can you please fix tests errors?

**Comment by u3u** [comment]
Of course, I've fixed it.

**Comment by rtivital** [comment]
Thanks!

**Pull request merged**
