### PR TITLE
[@mantine/core] TransferList: Add the `showSearch` prop.

### PR DESCRIPTION
**Pull request by Ultra-Instinct-05**
This PR proposes to add a `showSearch` prop to the `TransferList` component, which controls whether you want to show the search feature of `TransferList`. The motivation is that you may not need a search functionality all the time and a configuration option to turn it off is always nice. The default value for this prop is `true` for backwards compatibility.

### CODE REVIEW

**Comment by rtivital** [comment]
Please fix broken tests

**Comment by Ultra-Instinct-05** [comment]
Yup. Doing it currently. Forgot to run the linter before submitting the PR.

**Comment by Ultra-Instinct-05** [comment]
Any chance you could describe why that test has failed ? Because I can't make either head or tail of why that's failing.

**Comment by rtivital** [comment]
It failed because code is not formatted with prettier, you can view CI output by clicking “Details” button

**Comment by Ultra-Instinct-05** [comment]
I don't think it's an issue with prettier because running `npm run test` locally says

```
Checking formatting...
All matched files use Prettier code style!
```

It seems to be failing at this piece (which is something I don't understand). 

```
 FAIL  src/mantine-core/src/components/TransferList/TransferList.test.tsx
  ● @mantine/core/TransferList › uses styles api

    expect(received).not.toEqual(expected) // deep equality

    Expected: not [undefined, "test-transferListSearch"]

      20 |     styles.forEach((part) => {
      21 |       const node = part === 'root' ? element : element.find(`.mantine-${name}-${part}`);
    > 22 |       expect([node.attr('class'), `test-${part}`]).not.toEqual([undefined, `test-${part}`]);
         | ^
      23 |       expect(node.attr('class')).toContain(`test-${part}`);
      24 |     });
      25 |   });

      at src/mantine-tests/src/it-supports-styles-api.tsx:22:1
          at Array.forEach (<anonymous>)
      at Object.<anonymous> (src/mantine-tests/src/it-supports-styles-api.tsx:20:1)
```

**Comment by rtivital** [comment]
It says that `transferListSearch` class is not handled by styles api, it is `itSupportsStylesApi` test

**Comment by Ultra-Instinct-05** [comment]
I forgot to make the default value of the prop as `true`. Hence probably the failing test. I believe it should be good now.

**Comment by Ultra-Instinct-05** [comment]
I forgot to make the default value of the prop as `true`. Hence probably the failing test. I believe it should be good now.

**Comment by rtivital** [comment]
Thanks!

**Pull request merged**
