### PR TITLE
[docs] Fixed typo in cards page

### PR DESCRIPTION
**Pull request by WhyAsh5114**

### CODE REVIEW

**Comment by rtivital** [comment]
The fix is incorrect

**Comment by WhyAsh5114** [comment]
`It component is a first child in Card then it has negative top, left and right margins?`
I thought it should be It's?

**Comment by WhyAsh5114** [comment]
oh my bad, it should be if, ill make the changes

**Comment by rtivital** [comment]
Add more commits in this

**Comment by WhyAsh5114** [comment]
done, I hope its correct now

**Pull request merged**
