### PR TITLE
[@mantine/core] Modal: add centered prop

### PR DESCRIPTION
**Pull request by EmilMalanczak**

### CODE REVIEW

**Comment by cx0onl** [comment]
Awesome!

I was just about to propose the exact same feature and would have submitted the exact same PR!

**Comment by rtivital** [comment]
@EmilMalanczak centered prop does not work with `overflow="outside"` – modal title and close button are not visible, can you fix it in a PR?

Снимок экрана 2021-11-23 в 15 57 38

**Comment by EmilMalanczak** [comment]
is there anything that might work except `alignItems: centered && overflow !== 'outside' ? 'center' : 'flex-start'` ?

**Comment by rtivital** [comment]
Maybe there should be some padding top?

**Comment by EmilMalanczak** [comment]
I'll play around it to make it look nicer

**Comment by rtivital** [comment]
@EmilMalanczak have you looked at this, or should I work on this?

**Comment by EmilMalanczak** [comment]
completely forgot about it, i'll work on it now

**Comment by EmilMalanczak** [comment]
@rtivital can u look at this? I cannot see any other solution that this below. The con is that the overflow outside won't be centered when it won't be overflowing

> is there anything that might work except `alignItems: centered && overflow !== 'outside' ? 'center' : 'flex-start'` ?

**Comment by rtivital** [comment]
Okay, I'll have a look

**Pull request merged**
