### PR TITLE
Use `style` instead of `sx` to set thumb position

### LINKED ISSUE #1436: Slider component can have high CPU usage
### What package has an issue

@mantine/core

### Describe the bug

If the value of the slider changes often, the CPU is intensively used. This is because emotion needs to put new styles on the DOM because of the changing position. Probably, a fairly simple solution would be to use `style` instead of `sx` in the Thumb component to set the new position.

### In which browser did the problem occur

Any

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/friendly-hooks-vg11ph?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Use `style` instead of `sx` in the `Thumb` component

### PR DESCRIPTION
**Pull request by ramiel**
This should solve high CPU usage problems.

NOTE: there is one test failing, but it's independent of my changes, it's failing on main branch as well.

Closes #1436

### CODE REVIEW

**Comment by rtivital** [comment]
Does not work for RTL

https://user-images.githubusercontent.com/10353856/167854535-f80129f3-c111-4ac9-abf4-87db94ec73fb.mov

**Comment by ramiel** [comment]
I'll keep working on it later today

**Comment by ramiel** [comment]
Latest commit solves the problem and now it works on RTL as well. Though, I don't know if it's the right way of doing it and if this is the right approach to the problem. I don't know the system well enough. Maybe we can discuss it further?

**Comment by rtivital** [comment]
Thanks!

**Pull request merged**
