### PR TITLE
[@mantine/hooks] use-scroll-lock: migrate to internal state

### PR DESCRIPTION
**Pull request by yoroshikun**
Migrate to internal state handling.

Changed the API to maintain custom init state handling, please let me know if the naming and API is as intended or not.

Once I know what the API looks like I will update the docs accordingly

### CODE REVIEW

**Comment by rtivital** [comment]
Hi @yoroshikun thanks for PR, I think it will be better if we keep backwards compatibility with previous version and change
```tsx
useScrollLock({ lockOverride: true })
```
to
```tsx
useScrollLock(true)
```

**Comment by yoroshikun** [comment]
I was wondering how to handle the second optional argument this way.
{ disableTouchEvents } was an optional argument in the options passthough.
to access it without passing in a prop for override it would need to look like this.
```
useScrollLock(undefined, { disableTouchEvents: true})
```
as passing the first argument (the override) will make scroll lock controlled externally.

can you think of a more elegant solution?

**Comment by rtivital** [comment]
Well, that's a tricky situation, I guess the best option will be to remove `disableTouchEvents` logic all along, as it does not add any extra value and was added by my mistake.

**Comment by yoroshikun** [comment]
Updated to accommodate the requested changes.

Have also updated the docs page to reflect the changes.

**Comment by rtivital** [comment]
Thanks, works great, tested the backwards compatibility, works as expected

**Pull request merged**
