### PR TITLE
docs: added `pnpm` install guide and fix typo

### PR DESCRIPTION
**Pull request by dammy001**

### CODE REVIEW

**Comment by dammy001** [comment]
closes #855

**Comment by rtivital** [comment]
Thanks for a PR, but we do not need to display every existing package manager, yarn and npm is enough.

**Comment by dammy001** [comment]
@rtivital alright

**Comment by dammy001** [comment]
@rtivital i get your point. I can see that if we need to add pnpm, it will be added to a whole lot of pages.

**Pull request closed without merging**
