### PR TITLE
[@mantine/hooks] use-focus-trap: Fix animation bug for modal (#1753)

### PR DESCRIPTION
**Pull request by hotgen**

### CODE REVIEW

**Comment by rtivital** [comment]
Hi @hotgen, is this related to one of the open issues?

**Comment by hotgen** [comment]
@rtivital Hi, yes, it's fix for "slide-left transition looks off on modal with size set" #1753. The `focus` call shifts the scroll and thus breaks the animation.

**Comment by wes337** [comment]
This does seem to fix the bug in the issue. But are there other side effects to this solution? What if the `useFocusTrap` hook focuses an element outside the viewport, and we want to scroll?

**Comment by rtivital** [comment]
> What if the useFocusTrap hook focuses an element outside the viewport, and we want to scroll?

There should not be such case, focus trap should always be used on visible elements, any scrolling caused by use-focus-trap in unwanted. 

I was thinking that it will resolve the issue with Menu – #1982

**Comment by rtivital** [comment]
Thanks!

**Pull request merged**
