### PR TITLE
[@mantine/prism] Feature: allow overriding PrismTheme

### PR DESCRIPTION
**Pull request by fbartho**
PR implementing: https://github.com/mantinedev/mantine/discussions/1528#discussion-4104092

## Why

It'd be great if consumers could use @mantine/prism, while customizing the specific colors being selected for different language-tokens to better highlight what the user is trying to focus on.

Generally speaking, I find @mantine's color selections to be very legible, but as a slightly colorblind person, I strongly appreciate the ability to adjust which colors are selected for specific tokens.

By customizing the PrismTheme, a user can make specific tokens pop-out in a rendered code-block.

## How

Expose the call-site of `getPrismTheme` so users can provide their own method matching the same signature.
- https://github.com/mantinedev/mantine/blob/97349accc5632aefabb1a86d91a6f4b221e534cf/src/mantine-prism/src/Prism.tsx#L101-L106
- https://github.com/mantinedev/mantine/blob/97349accc5632aefabb1a86d91a6f4b221e534cf/src/mantine-prism/src/prism-theme.ts#L186-L187

### CODE REVIEW

**Comment by fbartho** [comment]
@rtivital please let me know if you want me to remake this PR targeting the v5 branch, or if you have any feedback. I’m happy to help contribute!

**Comment by rtivital** [comment]
Please remake this PR to target `master` branch, it can be released as a patch if there are no breacking changes

**Comment by rtivital** [comment]
@fbartho would you want to finish this PR?

**Comment by fbartho** [comment]
Commits cherry-picked cleanly to be on top of `master` in #1632

**Pull request closed without merging**
