### PR TITLE
[mantine.dev] Unify NumberFormatter and NumberInput prefixSuffix demo

### PR DESCRIPTION
**Pull request by mbarzda**
Hi,
  I changed `<NumberFormatter />` demo to use the same `prefix` and `suffix` values as in `<NumberInput />` demo.

### CODE REVIEW

**Comment by rtivital** [comment]
Why do you think that these changes should be made?

**Comment by mbarzda** [comment]
> Why do you think that these changes should be made?

Usually numeric input and output formatting should match in an application scope. I noticed the difference in Mantine's documentation and wanted to suggest a common look.

**Comment by rtivital** [comment]
Thanks for submitting the PR, but I'd rather keep the current demos

**Comment by mbarzda** [comment]
**Z**.

**Pull request closed without merging**
