### PR TITLE
Invalid initial value for "online" state in use-network hook (mantinedev#3177)

### PR DESCRIPTION
**Pull request by Sajarin-M**

### CODE REVIEW

**Comment by rtivital** [comment]
This change will cause hydration mismatch if used with ssr.

**Comment by Sajarin-M** [comment]
> This change will cause hydration mismatch if used with ssr.

Is there any other way to fix this

**Comment by rtivital** [comment]
No

**Comment by Sajarin-M** [comment]
does using `navigator.onLine` in the `useEffect` also cause a hydration mismatch ?

**Comment by rtivital** [comment]
No, it does not cause it, component rerenders on client.

**Comment by Sajarin-M** [comment]
then we can update it to correct state on rerender

**Comment by rtivital** [comment]
Thanks!

**Pull request merged**
