### PR TITLE
[@mantine/core] Table: Add a `border` prop.

### PR DESCRIPTION
**Pull request by Ultra-Instinct-05**
This PR adds a `border` prop to the `Table` component to render border to the table and all the table cells.

Reference: https://getbootstrap.com/docs/5.1/content/tables/#bordered-tables

### CODE REVIEW

**Comment by rtivital** [comment]
No, we do need this feature right now, please ask on Discord about features that you plan to contribute

**Comment by Ultra-Instinct-05** [comment]
What's the reason behind closing it ? Was there an issue in implemention details or something else ? It's discouraging when you put work in a PR and it gets rejected without a valid reason.

**Comment by rtivital** [comment]
Please see [contributing workflow](https://mantine.dev/pages/contributing/#contributing-workflow). You've decided that you do not want to discuss feature before coding, and your changes do go well with our planned backlog features.

**Comment by Ultra-Instinct-05** [comment]
> You've decided that you do not want to discuss feature before coding

Well, there were a number of other PR's I have made where I haven't discussed first in discord but were accepted. So I don't see how this is any different. I generally do this so that I am accountable to what I do. Proposing a feature & then failing to work looks kind of bad (at least for me). Anyways, I'll put forward in discord whatever I want to contribute in the future.

> your changes do go well with our planned backlog features.

Well, I assume you meant they `don't go well`. 🙂

**Comment by rtivital** [comment]
> Proposing a feature & then failing to work looks kind of bad

Not at all, it's always better to discuss feature first, if it is aligned with our plans you will be able to work on it (or someone else if you do not want to)

**Pull request closed without merging**
