### PR TITLE
Add onChangeEnd prop on ColorPicker component

### PR DESCRIPTION
**Pull request by DhrjArun**
**Prop**
> Just like Slider onChangeEnd prop
```onChangeEnd?: (value: string) => void;```

**Effected Components**
- ColorPicker
- ColorInput

### CODE REVIEW

**Comment by rtivital** [comment]
@DhrjArun `onChangeEnd` should be called:
- when user selects color by clicking on color swatch
- with valid value when user enters text in ColorInput

**Comment by DhrjArun** [comment]
@rtivital currently onChangeEnd is being called on
- arrow buttons
- saturation slider
- hue slider
- alpha slider

Do you want this behaviour?

**Comment by rtivital** [comment]
@DhrjArun It actually does not matter where onChangeEnd is called, what's important is that it is called every time user finishes picking color, this includes clicking color swatch and changing color in input

**Comment by DhrjArun** [comment]
@rtivital , let me know if anything is missing

**Comment by rtivital** [comment]
Works great, thanks!

**Pull request merged**
