### PR TITLE
[@mantine/core] TransferList: implement functionality for disabling items

### PR DESCRIPTION
**Pull request by PointSingularity**
This extends the 'TransferListItem' with an optional 'disabled' prop. If the item has it set to true, it won't be able to be selected.

Also adds the 'transferAllTransfersDisabled' prop (with default set to true) to the 'TransferList'.
I wanted to make it backward compatible, so transfer all still transfers all the items, including the disabled ones.
Setting this prop to false makes it so that the disabled items stay in their respective lists.

### CODE REVIEW

**Comment by PointSingularity** [comment]
Hey @rtivital if this is something you would want, I can adapt this to version 6?

**Comment by rtivital** [comment]
@PointSingularity I'll merge this as part of 6.1 release

**Comment by PointSingularity** [comment]
> @PointSingularity I'll merge this as part of 6.1 release

Great, thank you!

**Comment by rtivital** [comment]
Thanks for submitting a PR, it is closed because one of these reasons:
- The feature/bug fix has been implemented in [7.0.0](https://mantine.dev/changelog/7-0-0/)
- The feature is no longer relevant in 7.0.0
- You haven't followed [contribution workflow](https://mantine.dev/contribute/) and did not discuss the feature with a maintainer before submitting the PR

**Pull request closed without merging**
