### PR TITLE
[@mantine/core] Drawer: `withOverlay={false}` should let you click-through

### PR DESCRIPTION
**Pull request by italodeandra**

### CODE REVIEW

**Comment by rtivital** [comment]
Hi @italodeandra, we do not need separate prop for that, if `withOverlay` is set to false, then it should allow click thought.

**Comment by italodeandra** [comment]
Hey @rtivital,

I also thought that, but it only removes the overlay styles. To be able to click through, I still need to do this:

```tsx
<Drawer
    opened={opened}
    onClose={handleDrawerClose}
    title="Filme"
    padding="xl"
    size="xl"
    position="right"
    withOverlay={false}
    sx={{
      pointerEvents: "none",
      "& > *": {
        pointerEvents: "auto",
      },
    }}
  >
```

So perhaps I should remove the `clickThrough` from the Overlay and just keep `overlayClickThrough` on the Drawer?

**Comment by italodeandra** [comment]
> Check if `withOverlay={false}` and add those styles on library level, there is no need for extra prop for that.

Done.

**Comment by rtivital** [comment]
Thanks!

**Comment by ashishsurya** [comment]
I dont thibk this works

**Comment by heejj1206** [comment]
I don't think it's solved

**Comment by italodeandra** [comment]
Hey bros, my changes were removed by another PR a couple years ago. I don't use the lib anymore so I think you should create a new issue.

**Pull request merged**
