### PR TITLE
[@mantine/core] Cascader: Add component

### PR DESCRIPTION
**Pull request by tsar-boomba**
I started working on this for #757 back in March but got too busy to finish it. Well, now it's finally nearing completion.

This is what is done so far and what is left to do
- [x] Component
- [x] Stories
- [x] Tests
- [ ] Demos
- [ ] Docs

### CODE REVIEW

**Comment by zhulien-ivanov** [comment]
Please, attach a simple visual preview of the component here, if possible.

**Comment by tsar-boomba** [comment]
[example video](https://imgur.com/a/wDJy0ww)

**Comment by rtivital** [comment]
Please wait with this component until 6.0 release, there will be Select, MultiSelect and Autocomplete revamp

**Comment by tsar-boomba** [comment]
Waiting for v6.

**Pull request closed without merging**
