### PR TITLE
Add peer dependencies to @mantine/core and @mantine/next

### PR DESCRIPTION
**Pull request by MariaSolOs**
This PR adds a couple of peer dependencies:
- Both `@mantine/core` and `@mantine/next` depend on `@mantine/styles`, which has a peer dependency on `@emotion/react`.
- `@mantine/next` depends on `@mantine/ssr`, which has a peer dependency on `@emotion/server`.

### CODE REVIEW

**Comment by rtivital** [comment]
There is no need to describe peer dependencies in each package, it will only make dependencies versions harder to maintain. `@mantine/styles` and `@mantine/ssr` depending on `@emotion/*` packages is enough.

**Comment by MariaSolOs** [comment]
@rtivital Modern versions of `yarn` don't think that that's enough.
Here's the error message I obtain when installing the dependencies in a project using `yarn` 3.2.4:
image

**Comment by MariaSolOs** [comment]
If you wish, I could provide an example project with the issue @rtivital. 
I'm not trying to make things any harder for the library though, I'm just trying out Mantine for the first time and loving it so far! This is why I'm trying to contribute to make things better for everyone, specially Yarn users :)

**Comment by rtivital** [comment]
These changes can be breaking for some package managers, I'll change the dependencies with next major version

**Comment by rtivital** [comment]
Let's keep it opened as a reminder

**Pull request closed without merging**
