### PR TITLE
Update react-dropzone to 14.2.3 to fix OS issue

### PR DESCRIPTION
**Pull request by SrBrahma**
Fixes https://github.com/mantinedev/mantine/issues/2234

Update react-dropzone version from 14.2.2 to 14.2.3 to fix issues in some OS

"work around Chromium File System Access API bug": https://github.com/react-dropzone/react-dropzone/releases/tag/v14.2.3

### CODE REVIEW

**Comment by tianhuil** [comment]
@rtivital: this would be super helpful for us as we are encountering this issue also!

**Comment by rtivital** [comment]
Please make sure that yarn.lock is updated as well

**Comment by SrBrahma** [comment]
@rtivital lock file updated 💪

**Comment by SrBrahma** [comment]
There seems to have a "react-dropzone": "14.2.2" also in the root's package.json.

I will also bump it

**Comment by rtivital** [comment]
Please update the dependencies in all related package.json files, see failed job – https://github.com/mantinedev/mantine/actions/runs/3283725509/jobs/5409326425#step:8:20

**Comment by SrBrahma** [comment]
@rtivital Upgraded package in root package.json and lockfile updated

**Comment by rtivital** [comment]
Thanks!

**Pull request merged**
