### PR TITLE
[@mantine/core] Select: fixed the display of values in the dropdown i…

### PR DESCRIPTION
**Pull request by cheechoo28**
Issue example: https://codesandbox.io/s/serverless-framework-kl3vu3?file=/src/App.tsx
Issue description:
When I added a prop limit, after selecting the value, the dropdown is closed and if it is opened again, all values are displayed ignoring the limit.

### CODE REVIEW

**Comment by cheechoo28** [comment]
@rtivital That's what I intended. The idea is that two things are always shown in the dropdown . If nothing is selected, the first 3 are shown. If you have selected something, closed the dropdown and reopened, the first selected and subsequent ones are shown.

**Comment by rtivital** [comment]
Nope, this is not the correct logic that will create a lot of confusion

**Comment by cheechoo28** [comment]
@rtivital Well, I'll think about this problem again. I think the way it works now is also a confusion. I set the limit , but after I selected the value and reopened the dropdown , all the items are shown again

**Comment by cheechoo28** [comment]
@rtivital should now work correctly

**Comment by rtivital** [comment]
Thanks!

**Pull request merged**
