### PR TITLE
[@mantine/chart] fix: console error of barlabel

### PR DESCRIPTION
**Pull request by Kenzo-Wada**
fixes: https://github.com/mantinedev/mantine/issues/6800

### CODE REVIEW

**Review by ckifer — COMMENTED** [review]
LGTM, sorry those props are included. Generally its so they can be used in the recharts `Text` component I guess

**Comment by slk333** [comment]
thks for the PR

**Comment by slk333** [comment]
still not fixed as of 7.13 afaik

**Comment by Kenzo-Wada** [comment]
fixed the confict!

**Comment by rtivital** [comment]
Thanks!

**Pull request merged**
