### PR TITLE
Add MantineSize to shadow type for better DX

### PR DESCRIPTION
**Pull request by mosch**
See: https://github.com/mantinedev/mantine/pull/186

### CODE REVIEW

**Comment by rtivital** [comment]
Unfortunately this is not how TypeScript works: `'xs' | 'sm' | string` will just resolve to `string` and you will not get any value from adding MantineSize, try in [demo](https://www.typescriptlang.org/play?#code/C4TwDgpgBAglC8UDkBDJUA+yBGSDcAUKJFAMIKyZQDOwATgJYB2A5oQQGYCuTAxsAwD2TKNyYAKMCjooAtgC4yASigBvAlCh0IwLnRFSZswgF8C5seKVA)

Снимок экрана 2021-07-28 в 22 24 51

**Comment by mosch** [comment]
It still helps the IDE doing auto-complete suggestions. It's correct typescript and therefore it doesn't hurt but helps as documentation as well.

**Comment by rtivital** [comment]
> It still helps the IDE doing auto-complete suggestions
Can you provide an example of your IDE competition? VS Code does not show any autocomplete suggestions.

**Comment by mosch** [comment]
Well yeah. I couldn't get the suggestion to work on vscode as well. My bad. Thanks for the exchange.

**Comment by rtivital** [comment]
Hi @mosch, I've found a way to get autocomplete working, it should be
```tsx
type Size = 'xs' | 'sm' | 'md' | 'lg' | 'xl' | (string & {});
```

This will trigger autocomplete in vscode and allow any string as value

**Comment by mosch** [comment]
Whoa! What a weird, great thing. I'll test it.

**Pull request closed without merging**
