### PR TITLE
[@mantine/core] Fix indentation on List (listStylePosition: 'inside')

### LINKED ISSUE #2494: Keep the indentation with multiline contents of Item in List
### What package has an issue

@mantine/core

### Describe the bug

When content in List.Item is wrapping, it starts on start of a new line without the same space as mark has.
image

I think, this is because you use `list-style-position: inside`.
image

### What version of @mantine/hooks page do you have in package.json?

latest

### If possible, please include a link to a codesandbox with the reproduced problem

_No response_

### Do you know how to fix the issue

_No response_

### Are you willing to participate in fixing this issue and create a pull request with the fix

_No response_

### Possible fix

If this is a native list (no custom icon, etc..)
for `itemWrapper` use styles
```css
    display: inline-block;
    vertical-align: top;
    max-width: calc(100% - 1.5em);
```

or as for custom one use flex
```css
    display: inline-flex;
    flex-direction: column;
    max-width: calc(100% - 1.5em);
```

`1.5em` is a value of a dot width plus default space between it and content of item.

Currently, there is no other way to fix this, except to make a custom implementation for the default list types

### PR DESCRIPTION
**Pull request by 7iomka**
Revert #2528
Closes #2494

### CODE REVIEW

**Comment by rtivital** [comment]
Thanks!

**Comment by vrtischev** [comment]
@7iomka, I'll have to revert it, the PR broke the component – https://mantine.dev/core/list/#with-icons

**Comment by 7iomka** [comment]
> @7iomka, I'll have to revert it, unless you send a PR with a fix, the PR broke the component – https://mantine.dev/core/list/#with-icons

Nope, I'll fix now

**Comment by 7iomka** [comment]
@rtivital #2624

**Pull request merged**
