### PR TITLE
fix(CompDefaultProps): comp default props type

### PR DESCRIPTION
**Pull request by congyaqwq**
`defaultProps` passing to `useComponentDefaultProps` always return an optional type.

[ts playground demo](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAE2AYwDYEMrDgMwK4B2yMAlhAXHgM7ADCEAtpAcATACLA7p6owAKUCGCoB9AIwAeACpxQMVgipwASimgJJVGFBIEA5gBo46AgE8AfBYAUyRs1YwAXHG26DxpN14ChIl-yYpOioMhbGYH5ULtIAlDEA3ABQSaCQsIgoGFi4hMRkFNR09uSOnN58gsJiAEwyciAKBEqq6lCabnpGJubhcACqDU0tgbAkIWE2SXBwdkylbC6dHtOZFb7VLv2Gq5GbcNJJ8XAA3qsA2gDSwGZwenAAoiBoeEiSANY3EDgHxp9m3wGFgAujErjdgckAL5wABkpwu11u9yeOnQxA+Xx+0j+WKBwIAtAB+OBbcFmYFwg7k4FJKEpGBmMDYKoiOAAXgRMwI6AYwCWOi6yRmADcQnhgESBe59NCknYCNo4Ht-HBWcpOWdubz+XAAOTiGoAZj1O1F4t1ACJDUbLTt6fLyEqvDxKlEOVy4Dy+S4DcbTXSUgB6INqqKOxXwLBicQeor0eYsNjlV0bEQSax+k2eLip9URKKxODB0NnEMzCti1AS6VdOAAH0ozS4emACGS5Zh8LLoYrXp1tYMHdD9IVSujohqcZoCYcydzPnVk8zNtNazzUQL1ViSSAA)

### CODE REVIEW

**Comment by rtivital** [comment]
Hi @congyaqwq thanks for a PR! Can you please explain what this line means `[Key in Extract<keyof T, keyof U>]-? : U[Key] & T[Key]`? I've never seen `-?` such part anywhere else, can you send a link to ts documentation?

**Comment by congyaqwq** [comment]
It means remove optional `?` in an object type.

> You can remove or add these modifiers by prefixing with - or +. If you don’t add a prefix, then + is assumed.

[typescript mapped-types](https://www.typescriptlang.org/docs/handbook/2/mapped-types.html#mapping-modifiers)

**Comment by congyaqwq** [comment]
> 

Sorry, there was a test case can not pass in `useInputProps` fn.
`typescript` does not calc the type.
demo
[line 56](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAE2AYwDYEMrDgMwK4B2yMAlhAXHgM7ADCEAtpAcATACLA7p6owAKUCGCoB9AIwAeACpxQMVgipwASimgJJVGFBIEA5gBo46AgE8AfBYAUyRs1YwAXHG26DxpN14ChIl-yYpOioMhbGYH5ULtIAlDEA3ABQSaCQsIgoGFi4hMRkFNR09uSOnN58gsJiAEwyciAKBEqq6lCabnpGJubhcACqDU0tgbAkIWE2SXBwdkylbC6dHtOZFb7VLv2Gq5GbcNJJ8XAA2gDWwGYQOAMAukOKyueX1wf3APwHcC4A3qsnAGlLnA9HAAKIgNB4JCSC5XG7SYxw179Cy3GKAy63ZIAXzgADI4H8ZpizCCKBCdOhiLCXgikXSBmiALSfLak+6E6QcpI4lJpaDwPQKKDcZDYACSBDAeBgAHUoOgwGBgFAAELoGhVERE1YAegAVAa4FKZfAMAAjYCoTwkKhgDBmYAIOBWnDQbB6M1wA161aW63vJY6LrJfVGk3S2WZKjIXRgUjkW32x3Okw4EVwAOoH1+mZIWPxxMEIOuEMGMMzQ3G9h2h3oMzKVVCKBwBjAKhUdD6bDoDOq8ne32rZvQUumMyVuDVuAAQQQLSwLs1IrtZzg5DgMAAFthdPpt-AqCQkBubtnc6ssABHPAkJeli0QCCoYCmKcz7XKe1YdAumAQFm6BWjm1rAO2bCXjM2ZfqWah2O0Wjlt0E4WB+EZfq4kRvv+gEFnGJAJgUcivhB8DDvmHYEUR5CwS48EaEh7gob06HGphP44VugGjq2YFkVBchQC2dGtAhHTIcYqFsZG3p2Gw6B6AOcwOGwnhcDwfDKABrTUjAAB0ABiir6AJFGDrK9AKUpUDvLY24kKgCBYAQLgTscE4yVZOgvsoGgDq8O6SlGBkKkqKp8aRjjKOZXqymFyqqgA8u0qqltYADk2YZXAAA+cAZXFMA5flGX4UWBQlQVvEZbEJzYryKTCqqYrYBqWpRA8zTKKa8WKol6qasAmHEnAoiiNo6CkMgADKYHEGOwbMckMwnqWyz6Li-LgIKuREMWlA0L1GwiPU8iPHA7XDVEUwzCpCzOGWzE7JR6xfgEQTjKE0jhLsUQxEcup3eQ2gbkFUDKAAvIdxTzCwbDlJpJ21LYJTwzA6lvVEERRLEKRVnqByyMgphwAQEDwD28D7oeBxmCqqwwPT2DSLI0NMyqrwU7uENXsAMB4FAFDc6qVCNUkeqE+QqBklgygkxQVNwDT8Ac8ASTyaDctwNDRTHV+mUgEbGXGD82YuAAROINQAMwWzipvm3AVu2-beNJEAA)

```
  const {
    label,
    description,
    error,
    required,
    classNames,
    styles,
    className,
    unstyled,
    __staticSelector,
    sx,
    errorProps,
    labelProps,
    descriptionProps,
    wrapperProps,
    id,
    size,
    style,
    inputContainer,
    inputWrapperOrder,
    ...others
  } = useComponentDefaultProps(component, defaultProps, props);
```
the solution I think maybe need to update `defaultProps` type to `{[Key in T]-?: T[Key]}`, but It may be a large change. So I close the `PR`.
 I will reopen this `PR` if I get a new idea!

**Comment by rtivital** [comment]
Thanks!

**Pull request merged**
