### PR TITLE
[@mantine/core] make MantineThemeColorsOverride an interface instead of type

### PR DESCRIPTION
**Pull request by matheusvellone**
This is needed to allow `MantineThemeColorsOverride` to be overwritten

### CODE REVIEW

**Comment by matheusvellone** [comment]
Should I readd v6 docs section to v7 docs too? 
https://v6.mantine.dev/theming/colors/#add-custom-colors-types

**Comment by rtivital** [comment]
@matheusvellone please fix failing tests

**Comment by matheusvellone** [comment]
Done @rtivital

**Comment by rtivital** [comment]
Thanks!

**Pull request merged**
