### PR TITLE
Use headroom

### PR DESCRIPTION
**Pull request by BenHakimIlyass**
## Features
`use-headroom` is a hook that returns a boolean state which we can use to hide the header while scrolling and display it once the scroll goes backward

demo

✅ All tests passed
✅ All stories working as expected
❌ Couldn't get the stories displayed on the docs (might be an issue from my machine)

### CODE REVIEW

**Comment by dukesx** [comment]
Neat feature, Love it!

**Comment by AustinLeath** [comment]
this is awesome

**Comment by dukesx** [comment]
@rtivital please consider adding this hook. Iit really helps beating many heavy libraries out there trying to mimick the same behavior but in an inconveniently complex component setup with 70 to 100kb footprint.

**Comment by rtivital** [comment]
I'll merge this, I just do not have capacity to work on this atm

**Comment by dukesx** [comment]
Somebody merge this already. V6 is almost here and this neat hook seems to be ready

**Comment by rtivital** [comment]
Thanks!

**Pull request merged**
