### PR TITLE
[@mantine/core] MultiSelect - minor fixes

### PR DESCRIPTION
**Pull request by achmurali**
- fix dropdown opening when `maxSelectedValues` is reached
- fix `creatable` when using useForm

### CODE REVIEW

**Comment by rtivital** [comment]
@achmurali do you know if this PR will fix this issue #2059?

**Comment by achmurali** [comment]
> @achmurali do you know if this PR will fix this issue #2059?

I haven't investigated that, will try to address that as well.

**Comment by rtivital** [comment]
Great, thanks!

**Comment by dipiash** [comment]
@achmurali Hi!
I have just finished investigate this issue https://github.com/mantinedev/mantine/issues/2059, and it solve problems with dropdown with all selected items and text input to searching

My problem also solved: https://github.com/mantinedev/mantine/issues/2059#issuecomment-1216447251

**Comment by rtivital** [comment]
Thanks!

**Pull request merged**
