### PR TITLE
[@mantine/core] NumberInput: Add decimal separator prop

### PR DESCRIPTION
**Pull request by jerebtw**
https://github.com/mantinedev/mantine/issues/521

### CODE REVIEW

**Comment by LucasLemanowicz** [comment]
Thoughts on taking advantage of the JS built-in Intl.NumberFormat API? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat

Added benefit that it would allow for other types of formatting (such as currencies), and also provide better integration with other JS libraries.

**Comment by rtivital** [comment]
@LucasLemanowicz the problem with NumberFormat is that we need to convert formatted number back to number value and I do not know a good way to do so

**Comment by rtivital** [comment]
@jerebtw can you please resolve conflicts?

**Comment by jerebtw** [comment]
I resolved the conflicts

**Comment by ruessej** [comment]
I will fix the error later when im at home

**Comment by jerebtw** [comment]
Cleaned version: https://github.com/mantinedev/mantine/pull/535

**Pull request closed without merging**
