### PR TITLE
[@mantine/core] PasswordInput: fix selected text style

### PR DESCRIPTION
**Pull request by lawff**
#2468, just modify the height to bigger than the line-height

### CODE REVIEW

**Comment by rtivital** [comment]
Hi @lawff, this change makes input content misaligned vertically
Снимок экрана 2022-09-16 в 17 05 45

**Comment by rickmoens** [comment]
Adding `vertical-align: middle` to the input seems to fix it.

**Comment by lawff** [comment]
> Hi @lawff, this change makes input content misaligned vertically Снимок экрана 2022-09-16 в 17 05 45

sorry, I made a mistake. Now, I add the border to the inner input to solve the misaligned vertically, I need your advice if this solution is helpful.

**Comment by rtivital** [comment]
Works great, thanks!

**Pull request merged**
