### PR TITLE
Fix use-in-viewport when ref changes

### PR DESCRIPTION
**Pull request by fellmann**
Fixes https://github.com/mantinedev/mantine/issues/6812

### CODE REVIEW

**Comment by rtivital** [comment]
Please fix errors in tests.

**Comment by rtivital** [comment]
Have you validated that the solution works as expected?

**Comment by fellmann** [comment]
It is working in my application, and as I understand it works for https://github.com/mantinedev/mantine/issues/6812#issuecomment-2383626076 too.

**Comment by rtivital** [comment]
Great, thanks!

**Pull request merged**
