### PR TITLE
[@mantine/hooks] add reusable return type for hooks

### PR DESCRIPTION
**Pull request by jimmyruann**
#1020

### CODE REVIEW

**Comment by rtivital** [comment]
Types are not exported from index.ts, and thus they will not be accessible from `@mantine/hooks` package

**Comment by jimmyruann** [comment]
Thank you for that. Will fix that up.

**Comment by rtivital** [comment]
I do not think that most of these hooks require types export, maybe some state hooks can benefit from that, but adding these types to all of the hooks will hurt readability and make maintenance more complex.

**Comment by jimmyruann** [comment]
Thank you for the feedback @rtivital . I will reassess the each hooks and create a new PR.

**Pull request closed without merging**
